/* Demo mode: three saved cards, so Moneta can make its point with no bank card
 * in the room — at a talk, in a classroom, or in a screenshot.
 *
 * The demo does not fabricate a result. It replays real EMV response bytes
 * (helpers/demo_card_data.h, generated by tools_gen_demo.py) through the same
 * emv_card parser the radio path uses. If the parser regresses, the demo
 * regresses with it, which is the only arrangement worth trusting.
 */
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "emv_card.h"

#ifdef __cplusplus
extern "C" {
#endif

size_t demo_card_count(void);
const char* demo_card_title(size_t index);
const char* demo_card_blurb(size_t index);

/* Parse demo card `index` into `card`. Returns false for an out-of-range
 * index, leaving `card` reset. */
bool demo_card_load(size_t index, EmvCard* card);

#ifdef __cplusplus
}
#endif
